# Generated by Django 5.1.15 on 2026-04-26 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concepts', '0001_initial'),
        ('procedures', '0002_procedure_best_practices_procedure_common_pitfalls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('config', 'Configuration'), ('securite', 'Securite'), ('troubleshooting', 'Troubleshooting'), ('reference', 'Reference'), ('formation', 'Formation'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('tags', models.CharField(blank=True, help_text='Tags separes par virgule', max_length=300)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('text', 'Texte / Markdown')], default='pdf', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/%Y/%m/')),
                ('html_content', models.TextField(blank=True, help_text='Contenu HTML (si type HTML sans fichier)')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='concepts.networkconcept')),
                ('related_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Document technique',
                'verbose_name_plural': 'Documents techniques',
                'ordering': ['-created_at'],
            },
        ),
    ]
