# Generated by Django 5.1.15 on 2026-04-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='bi-folder', max_length=50, verbose_name='Icône Bootstrap')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(max_length=300, verbose_name='Résumé court')),
                ('objective', models.TextField(verbose_name='Objectif')),
                ('use_cases', models.TextField(blank=True, verbose_name="Cas d'usage")),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prérequis')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('vendor', models.CharField(choices=[('cisco', 'Cisco'), ('fortinet', 'Fortinet'), ('paloalto', 'Palo Alto'), ('juniper', 'Juniper'), ('aruba', 'Aruba / HP'), ('generic', 'Générique')], default='cisco', max_length=20, verbose_name='Vendor')),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('router', 'Routeur'), ('firewall', 'Firewall'), ('wireless', 'Contrôleur Wifi'), ('generic', 'Générique')], default='switch', max_length=20, verbose_name="Type d'équipement")),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='intermediate', max_length=20, verbose_name='Difficulté')),
                ('estimated_duration', models.PositiveSmallIntegerField(default=15, verbose_name='Durée estimée (min)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('review', 'En révision'), ('published', 'Publiée'), ('deprecated', 'Dépréciée')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='procedures.procedurecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Procédure',
                'verbose_name_plural': 'Procédures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('pre', 'Pré-check'), ('post', 'Post-check'), ('validation', 'Validation'), ('troubleshooting', 'Dépannage')], max_length=20, verbose_name='Type de check')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('command', models.TextField(verbose_name='Commande')),
                ('expected_output', models.TextField(blank=True, verbose_name='Sortie attendue')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
                'ordering': ['check_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureRollback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(verbose_name='Conditions de rollback')),
                ('rollback_commands', models.TextField(verbose_name='Commandes de rollback')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rollback', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Rollback',
                'verbose_name_plural': 'Rollbacks',
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(verbose_name="N° d'étape")),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'étape")),
                ('explanation', models.TextField(verbose_name='Explication')),
                ('command_template', models.TextField(blank=True, help_text='Utiliser {{ nom_variable }} pour les variables dynamiques', verbose_name='Template de commandes')),
                ('expected_result', models.TextField(blank=True, verbose_name='Résultat attendu')),
                ('warning', models.TextField(blank=True, verbose_name='Avertissement')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Étape',
                'verbose_name_plural': 'Étapes',
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom utilisé dans le template (ex: vlan_id)', max_length=60, verbose_name='Nom de variable')),
                ('label', models.CharField(max_length=100, verbose_name='Label affiché')),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('ip', 'Adresse IP'), ('subnet', 'Masque de sous-réseau'), ('vlan', 'ID VLAN'), ('interface', 'Interface'), ('select', 'Liste de choix')], default='text', max_length=20, verbose_name='Type de champ')),
                ('placeholder', models.CharField(blank=True, max_length=100)),
                ('default_value', models.CharField(blank=True, max_length=100)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'ordering': ['order', 'name'],
            },
        ),
    ]
