# Generated by Django 5.1.15 on 2026-04-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='best_practices',
            field=models.TextField(blank=True, verbose_name='Bonnes pratiques'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='common_pitfalls',
            field=models.TextField(blank=True, verbose_name='Pièges fréquents'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='criticality',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Criticité'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='expected_outcome',
            field=models.TextField(blank=True, verbose_name='Résultat attendu'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='platform',
            field=models.CharField(choices=[('ios', 'Cisco IOS'), ('ios-xe', 'Cisco IOS-XE'), ('nx-os', 'Cisco NX-OS'), ('asa', 'Cisco ASA'), ('fortios', 'FortiOS'), ('junos', 'JunOS'), ('generic', 'Générique')], default='ios', max_length=20, verbose_name='Plateforme'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='requires_maintenance_window',
            field=models.BooleanField(default=False, verbose_name='Fenêtre de maintenance requise'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='save_config_required',
            field=models.BooleanField(default=True, verbose_name='Sauvegarde de config requise'),
        ),
        migrations.AddField(
            model_name='procedurevariable',
            name='select_options',
            field=models.CharField(blank=True, help_text="Pour le type 'select' uniquement. Ex: GigabitEthernet,FastEthernet,TenGigabit", max_length=500, verbose_name='Options (séparées par virgule)'),
        ),
        migrations.AlterField(
            model_name='procedurecheck',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='procedurerollback',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes de prudence'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='command_template',
            field=models.TextField(blank=True, help_text='Utiliser {{ nom_variable }} pour les substitutions dynamiques', verbose_name='Template de commandes'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='procedurevariable',
            name='default_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valeur par défaut'),
        ),
        migrations.AlterField(
            model_name='procedurevariable',
            name='help_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Aide contextuelle'),
        ),
        migrations.AlterField(
            model_name='procedurevariable',
            name='name',
            field=models.CharField(help_text='Identifiant utilisé dans les templates (ex: vlan_id)', max_length=60, verbose_name='Nom de variable'),
        ),
        migrations.AlterField(
            model_name='procedurevariable',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='procedurevariable',
            name='placeholder',
            field=models.CharField(blank=True, max_length=100, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='procedurevariable',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Requis'),
        ),
    ]
