# Generated by Django 6.0.4 on 2026-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_procedure_best_practices_procedure_common_pitfalls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurestep',
            name='real_world_example',
            field=models.TextField(blank=True, verbose_name='Exemple concret'),
        ),
    ]
