# Generated by Django 5.1.15 on 2026-04-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('module_number', models.PositiveSmallIntegerField(default=1)),
                ('module_name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('base', 'Base'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance')], default='base', max_length=20)),
                ('icon', models.CharField(default='bi-lightbulb', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('simple_explanation', models.TextField()),
                ('concrete_example', models.TextField()),
                ('technical_version', models.TextField()),
                ('summary', models.CharField(max_length=300)),
                ('quiz_q1', models.CharField(max_length=300)),
                ('quiz_a1', models.TextField()),
                ('quiz_q2', models.CharField(max_length=300)),
                ('quiz_a2', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concept reseau',
                'verbose_name_plural': 'Concepts reseau',
                'ordering': ['module_number', 'order'],
            },
        ),
    ]
